# Generated by Django 2.2 on 2020-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_qs_app', '0003_auto_20200924_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
